services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: batmap-api
    ports:
      - "8000:8000"
    volumes:
      - ./map_store:/app/map_store
      - ./data.db:/app/data.db
    environment:
      - PYTHONUNBUFFERED=1

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: batmap-web
    ports:
      - "8080:80"
    volumes:
      - ./web-client:/usr/share/nginx/html:ro
    environment:
      - API_PROXY_PASS=http://api:8000/
